export const
    // primary
    NUMBER = 'NUMBER',
    STRING = 'STRING',
    IDENTIFIER = 'IDENTIFIER',
    IDENTIFIER_REFERENCE = 'IDENTIFIER_REFERENCE',
    THIS = 'THIS',
    OBJECT = 'OBJECT',

    // object
    PROPERTY_NAME = 'PROPERTY_NAME',
    SPREAD = 'SPREAD',
    PROPERTY_REF = 'PROPERTY_REF',
    ARRAY_REF = 'ARRAY_REF',
    SUPER_PROPERTY = 'SUPER_PROPERTY',

    // call
    CALL = 'CALL',
    NEW = 'NEW',
    SUPER_CALL = 'SUPER_CALL',

    // operation
    UNARY_OPERATOR = 'UNARY_OPERATOR',
    BINARY_OPERATOR = 'BINARY_OPERATOR',
    INCREMENT = 'INCREMENT',
    DECREMENT = 'DECREMENT',
    ASSIGNMENT = 'ASSIGNMENT',

    // statement
    EXPRESSION_STATEMENT = 'EXPRESSION_STATEMENT',
    IF = 'IF',
    SWITCH = 'SWITCH',
    WHILE = 'WHILE',
    FOR = 'FOR',
    BREAK = 'BREAK',
    CONTINUE = 'CONTINUE',
    RETURN = 'RETURN',
    STATEMENTS = 'STATEMENTS',
    BLOCK = 'BLOCK',

    // variable
    BINDINGS = 'BINDINGS',
    INITIALIZE = 'INITIALIZE',

    // function
    FUNCTION_DECLARATION = 'FUNCTION_DECLARATION',
    FUNCTION_EXPRESSION = 'FUNCTION_EXPRESSION',

    // method
    METHOD_DEFINITION = 'METHOD_DEFINITION',
    GETTER_METHOD_DEFINITION = 'GETTER_METHOD_DEFINITION',
    SETTER_METHOD_DEFINITION = 'SETTER_METHOD_DEFINITION',

    // class
    CLASS_DECLARATION = 'CLASS_DECLARATION'
;
