export const
    NUMBER = 'NUMBER',
    STRING = 'STRING',
    IDENTIFIER = 'IDENTIFIER',
    IDENTIFIER_REFERENCE = 'IDENTIFIER_REFERENCE',
    MEMBER = 'MEMBER',
    CALL = 'CALL',
    ARGUMENTS = 'ARGUMENTS',
    UNARY_OPERATOR = 'UNARY_OPERATOR',
    BINARY_OPERATOR = 'BINARY_OPERATOR',
    INCREMENT = 'INCREMENT',
    DECREMENT = 'DECREMENT',
    ASSIGNMENT = 'ASSIGNMENT',
    BLOCK = 'BLOCK',
    EXPRESSION_STATEMENT = 'EXPRESSION_STATEMENT',
    BINDINGS = 'BINDINGS',
    INITIALIZE = 'INITIALIZE',
    STATEMENTS = 'STATEMENTS'
;
